"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";
import ThemeContextProvider from "@/context/theme-context";
import { Analytics } from "@vercel/analytics/react";
import ThemeSwitch from "@/components/theme-switch";

import netflix from "@/public/netflix.png";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "WTF",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <title>Hridoy portfolio</title>
      <Head>
        <meta
          name="description"
          content="Dev Hridoy portfolio website, where you can find about his career"
          key="desc"
        />
        <meta property="og:title" content="Hridoy Portfolio" />
        <meta
          property="og:description"
          content="Check out my work and see what I've been working on!"
        />
        <meta property="og:image" content={netflix} />
      </Head>
      <body
        className={`${inter.className} dark:bg-[#232722] dark:text-white bg-gray-50 relative text-gray-950 pt-32 sm:pt-40 `}
      >
        {/* <Navbar/> */}
        <div className="bg-[#fbe2e3] dark:bg-[#4f3f88] absolute top-[-6rem] right-[11rem] -z-10 h-[31.25rem] w-[31.25rem]  rounded-full blur-[10rem] sm:w-[68.75rem]"></div>
        <div className="bg-[#dbd7fb] dark:bg-[#1e1930] absolute top-[-1rem] left-[-35rem] -z-10 h-[31.25rem] w-[50rem]  rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"></div>
        {/* NEW Color Test */}
        {/* <div className="bg-[#498996] absolute top-[-6rem] right-[11rem] -z-10 h-[31.25rem] w-[31.25rem]  rounded-full blur-[10rem] sm:w-[68.75rem]"></div>
          <div className="bg-[#afbdac] absolute top-[-1rem] left-[-35rem] -z-10 h-[31.25rem] w-[50rem]  rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"></div> */}
        <ThemeContextProvider>
          <ActiveSectionContextProvider>
            <Header />
            {children}
            <Analytics />
            <Footer />
            <Toaster position="bottom-left" />
          </ActiveSectionContextProvider>
          <ThemeSwitch />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
